MODULE AACGM
DESCRIPTION AACGM
VERSION 3.8
SOURCE Haje Korth, JHU/APL
BUILD_DATE December 2009
FUNCTION AACGM_MLONG 3 3
FUNCTION AACGM_MLT 3 3 KEYWORDS
PROCEDURE AACGM_CONV_COORD 6 6 KEYWORDS
PROCEDURE AACGM_HELP 0 0
PROCEDURE AACGM_LOAD_COEF 1 1 KEYWORDS
PROCEDURE AACGM_SET_PATH 1 1 KEYWORDS
PROCEDURE AACGM_CONV_VEC 12 12 KEYWORDS
